# Generated by Django 3.2.8 on 2021-11-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
    ]
